site_name: EvoAgentX
theme:
  name: material
  custom_dir: docs/overrides
  font:
    text: Exo 2
    code: Fira Code
  icon:
    repo: fontawesome/brands/git-alt 
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    # - header.autohide
    - navigation.sections 
    - navigation.expand 
    - navigation.footer
    - navigation.path
    - content.code.select
    - content.code.copy 
    - navigation.indexes
    - navigation.expand
    - navigation.tabs
    - content.tabs.link
    - navigation.top
    - navigation.tracking
    - navigation.search.highlight
    - navigation.search.share
    - navigation.search.suggest
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - content.code.annotate
    - content.heading.auto-number 
    # - navigation.tabs.sticky
    - toc.follow
    - announce.dismiss 
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  # icon:
  #   repo: fontawesome/brands/github

# Repository
repo_url: https://github.com/EvoAgentX/EvoAgentX
repo_name: EvoAgentX
# repo_type: github

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EvoAgentX/EvoAgentX
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/EvoAgentX
    - icon: fontawesome/brands/discord
      link: https://discord.gg/EvoAgentX
    - icon: fontawesome/solid/envelope
      link: mailto:evoagentx.ai@gmail.com
  generator: false

copyright: Copyright Â© 2025 EvoAgentX Team.

markdown_extensions:
  - toc:
      title: On this page
      # icon: material/link
      permalink: true
      toc_depth: 3
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.caret


nav:
  # - Home: index.md
  - Getting Started:
    - Home: index.md
    - Install: installation.md 
    - Quickstart: quickstart.md
  - Tutorials:
    - Build Your First Agent: tutorial/first_agent.md
    - Build Your First Workflow: tutorial/first_workflow.md
    - Benchmark and Evaluation: tutorial/benchmark_and_evaluation.md
    - AFlow Optimizer: tutorial/aflow_optimizer.md
    - SEW Optimizer: tutorial/sew_optimizer.md
  - Key Modules:
    - LLM: modules/llm.md 
    - Agent: modules/agent.md
    - Customize Agent: modules/customize_agent.md
    - Workflow Graph: modules/workflow_graph.md
    - Action Graph: modules/action_graph.md
    - Benchmark: modules/benchmark.md 
    - Evaluator: modules/evaluator.md 
  - API Reference:
    - Core: api/core.md
    - Models: api/models.md
    - Agents: api/agents.md
    - Workflow: api/workflow.md
    - Storages: api/storages.md
    - Memory: api/memory.md
    - Tools: api/tools.md 
    - Actions: api/actions.md
    - Benchmark: api/benchmark.md
    - Evaluators: api/evaluators.md
    - Optimizers: api/optimizers.md


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 3
            # show_root_heading: true
            show_source: true
            merge_init_into_class: true
            show_signature: true
            show_docstring: true
            separate_signature: true
            members_order: source
            signature_crossrefs: true
            show_signature_annotations: ture